# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	if Vagrant.has_plugin? "vagrant-vbguest"
		config.vbguest.no_install  = true
		config.vbguest.auto_update = false
		config.vbguest.no_remote   = true
	end
	config.vm.define :dockerUbuntu do |dockerUbuntu|
		dockerUbuntu.vm.box = "bento/ubuntu-20.04"
		dockerUbuntu.vm.network :private_network, ip: "192.168.100.4"
		dockerUbuntu.vm.hostname = "dockerUbuntu"
		dockerUbuntu.vm.provision "file", source: "Dockerfile", destination: "/home/vagrant/Dockerfile"
		dockerUbuntu.vm.provision "file", source: "run-vsftpd.sh", destination: "/home/vagrant/run-vsftpd.sh"
		dockerUbuntu.vm.provision "file", source: "vsftpd.conf", destination: "/home/vagrant/vsftpd.conf"
		dockerUbuntu.vm.provision "shell", path: "script_docker.sh"
		dockerUbuntu.vm.provider "virtualbox" do |v|
			v.name = "dockerUbuntu_ftp"
			v.memory = 2048
			v.cpus = 2
		end
	end
end
