FROM jupyter/minimal-notebook

MAINTAINER wilmer1022 <guarind487@gmail.com>
RUN pip install tensorflow
RUN pip install preprocess1
RUN pip install scikit-learn
RUN pip install opencv-python
RUN pip install numpy
RUN pip install pandas
RUN pip install matplotlib

VOLUME ["/home/jovyan/work/"]